clients:
  sbom:
    service_url: https://sbom-request.canonical.com
    department: charm_engineering
    email: tony.meyer@canonical.com
    team: charm_tech
  secscan: {}

artifacts:
  - name: 'pytest-jubilant'
    type: 'sdist'
    compression: 'gz'
    source: 'dist/pytest_jubilant-__VERSION__.tar.gz'
    ssdlc_params:
      name: 'pytest-jubilant'
      version: ''
      channel: 'stable'

  - name: 'pytest-jubilant'
    type: 'wheel'
    source: 'dist/pytest_jubilant-__VERSION__-py3-none-any.whl'
    ssdlc_params:
      name: 'pytest-jubilant'
      version: ''
      channel: 'stable'
