# Copyright 2023 Canonical
# See LICENSE file for licensing details.

[tox]
isolated_build = True
skip_missing_interpreters = True
envlist = lint, unit

[testenv]
runner = uv-venv-lock-runner
setenv =
  PY_COLORS=1

[testenv:unit]
description = Run unit tests
dependency_groups = unit
commands =
    coverage run --source {toxinidir}/pytest_jubilant --branch -m \
        pytest --tb=native -vv --log-cli-level=DEBUG {toxinidir}/tests/unit {posargs}
    coverage report

[testenv:integration]
description = Run integration tests
dependency_groups = integration
pass_env =
    *CHARM_PATH
    TMPDIR
commands =
    coverage run --source {toxinidir}/pytest_jubilant --branch -m \
        pytest --tb=native -vv --log-cli-level=DEBUG {toxinidir}/tests/integration {posargs}
    coverage report

[testenv:lint]
description = Check code style and type correctness
dependency_groups = lint, unit, integration
commands =
    ruff format --preview --check
    ruff check --preview
    pyright {posargs}

[testenv:format]
description = Apply coding style standards to code
dependency_groups = lint
commands =
    ruff format --preview
    ruff check --preview --fix {posargs}  # intended for passing --unsafe-fixes
