# Copyright 2023 Canonical
# See LICENSE file for licensing details.

[tox]
isolated_build = True
skip_missing_interpreters = True
envlist = lint, unit

[testenv]
runner = uv-venv-lock-runner
setenv =
  PY_COLORS=1


[testenv:unit]
description = run unittests
dependency_groups = unit
commands =
    coverage run --source {toxinidir}/pytest_jubilant --branch -m \
        pytest -v --tb native {toxinidir}/tests --tb=native -vv {posargs}
    coverage report


[testenv:lint]
description = Check code style and type correctness
dependency_groups = lint, unit
commands =
    ruff format --preview --check
    ruff check --preview
    pyright {posargs}


[testenv:format]
description = Apply coding style standards to code
dependency_groups = lint
commands =
    ruff format --preview
    ruff check --preview --fix {posargs}  # intended for passing --unsafe-fixes
