name: Integration Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.tests.outputs.result }}
      charms: ${{ steps.charms.outputs.result }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
      - name: Collect integration tests
        id: tests
        run: |
          set -xueo pipefail
          result=$(uv run --group integration pytest --collect-only -q --no-header tests/integration | grep '::' | jq -Rnc '[inputs]')
          echo "result=$result" >> "$GITHUB_OUTPUT"
      - name: Collect charm directories
        id: charms
        run: |
          set -xueo pipefail
          result=$(find tests/integration/charms -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | jq -Rnc '[inputs]')
          echo "result=$result" >> "$GITHUB_OUTPUT"

  pack:
    needs: [init]
    strategy:
      fail-fast: true
      matrix:
        charm: ${{ fromJson(needs.init.outputs.charms) }}
    runs-on: ubuntu-24.04  # matching the charms' base for destructive mode packing
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - run: sudo snap install --classic charmcraft
      - run: sudo charmcraft pack --destructive-mode
        working-directory: tests/integration/charms/${{ matrix.charm }}
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.charm }}-charm
          path: "tests/integration/charms/${{ matrix.charm }}/*.charm"
          if-no-files-found: error

  test:
    needs: [init, pack]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.init.outputs.tests) }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - run: sudo snap install --classic concierge
      - run: sudo concierge prepare -c .github/concierge/test.yaml
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
      - uses: actions/download-artifact@v8
        with:
          pattern: "*-charm"
          merge-multiple: true
      - name: Set *CHARM_PATH env vars
        run: |
          for charm in *.charm; do
            name=${charm%%_*}  # strip from first underscore to end: simple_amd64.charm -> simple
            name=${name//-/_}  # replace hyphens with underscores: my-charm -> my_charm
            # uppercase and append suffix: simple -> SIMPLE_CHARM_PATH
            echo "${name^^}_CHARM_PATH=${{ github.workspace }}/${charm}" >> "$GITHUB_ENV"
          done
      - run: uv run --only-group tox tox -e integration -- "$MATRIX_TEST"
        env:
          MATRIX_TEST: ${{ matrix.test }}
          TMPDIR: ${{ github.workspace }}
