name: Tests

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
      - run: uv tool install tox --with tox-uv
      - run: tox -e lint

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
      - run: uv tool install tox --with tox-uv
      - run: tox -e unit

  run-integration:
    needs: [lint, unit]
    uses: ./.github/workflows/integration.yaml
    permissions:
      actions: write
      contents: read

  integration:
    needs: [run-integration]
    if: ${{ !cancelled() }}  # run even if tests are skipped or failed
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any tests failed
        if: ${{ needs.run-integration.result != 'success' }}
        run: exit 1
