name: Tests

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
      - run: uv run --only-group tox tox -e lint

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
      - run: uv run --only-group tox tox -e unit

  run-integration:
    needs: [lint, unit]
    uses: ./.github/workflows/integration.yaml
    permissions:
      actions: write
      contents: read

  integration:
    needs: [run-integration]
    if: ${{ !cancelled() }}  # run even if tests are skipped or failed
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any tests failed
        if: ${{ needs.run-integration.result != 'success' }}
        run: exit 1
