name: TIOBE

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * 0'

permissions: {}

jobs:
  TICS:
    runs-on: [self-hosted, reactive, amd64, tiobe, noble]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0

        # We could store the coverage report from the regular run, but this is cheap to do
        # and keeps this isolated.
      - name: Run unit tests and generate coverage report
        run: |
          uv run --only-group tox tox -e unit
          mkdir .report
          uv run --only-group unit coverage xml -o .report/coverage.xml

        # Note that these are dependencies for the tools that the TIOBE action will run,
        # which is done in the global environment, rather than a venv, as we do with the
        # unit tests. Versions for flake8 and pylint are pinned via the `tiobe`
        # dependency group in pyproject.toml.
      - name: Install dependencies
        run: |
          uv export --no-emit-project --frozen --no-hashes --group tiobe > requirements.txt
          pip install -r requirements.txt --break-system-packages

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@016a4d79f3027fe7b4a2901619a58c745ab7cadf  # v3.10.0
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: pytest-jubilant
          installTics: true
